# Generated by Django 5.0.6 on 2024-06-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='type',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
