# Generated by Django 5.0.6 on 2024-06-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelRecord', '0002_hostel_type_alter_hostel_address_alter_hostel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room_number',
        ),
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='HostelRecord.hostel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
