# Generated by Django 5.0.6 on 2024-06-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelRecord', '0003_remove_student_room_number_student_hostel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='HostelRecord.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelRecord.hostel'),
        ),
    ]
